-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."CinemaHalls"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "OpenDate" timestamp with time zone NOT NULL,
    "CloseDate" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_CinemaHalls" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Movies"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Title" text COLLATE pg_catalog."default" NOT NULL,
    "Description" text COLLATE pg_catalog."default",
    "PosterImg" text COLLATE pg_catalog."default",
    "DurationTime" integer NOT NULL,
    CONSTRAINT "PK_Movies" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Reservations"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "BookedSeanceId" integer,
    "IsReturnable" boolean NOT NULL,
    "UserId" integer,
    CONSTRAINT "PK_Reservations" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Seances"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "MovieId" integer,
    "CinemaHallId" integer,
    CONSTRAINT "PK_Seances" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Seats"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Number" integer NOT NULL,
    "IsFree" boolean NOT NULL,
    "IsChoosed" boolean NOT NULL,
    "SeanceId" integer,
    "ReservationsId" integer,
    CONSTRAINT "PK_Seats" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Users"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Username" text COLLATE pg_catalog."default",
    "Password" text COLLATE pg_catalog."default",
    "Firstname" text COLLATE pg_catalog."default",
    "Lastname" text COLLATE pg_catalog."default",
    "IsAdmin" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."__EFMigrationsHistory"
(
    "MigrationId" character varying(150) COLLATE pg_catalog."default" NOT NULL,
    "ProductVersion" character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

ALTER TABLE IF EXISTS public."Reservations"
    ADD CONSTRAINT "FK_Reservations_Seances_BookedSeanceId" FOREIGN KEY ("BookedSeanceId")
    REFERENCES public."Seances" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Reservations_BookedSeanceId"
    ON public."Reservations"("BookedSeanceId");


ALTER TABLE IF EXISTS public."Reservations"
    ADD CONSTRAINT "FK_Reservations_Users_UserId" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Reservations_UserId"
    ON public."Reservations"("UserId");


ALTER TABLE IF EXISTS public."Seances"
    ADD CONSTRAINT "FK_Seances_CinemaHalls_CinemaHallId" FOREIGN KEY ("CinemaHallId")
    REFERENCES public."CinemaHalls" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Seances_CinemaHallId"
    ON public."Seances"("CinemaHallId");


ALTER TABLE IF EXISTS public."Seances"
    ADD CONSTRAINT "FK_Seances_Movies_MovieId" FOREIGN KEY ("MovieId")
    REFERENCES public."Movies" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Seances_MovieId"
    ON public."Seances"("MovieId");


ALTER TABLE IF EXISTS public."Seats"
    ADD CONSTRAINT "FK_Seats_Reservations_ReservationsId" FOREIGN KEY ("ReservationsId")
    REFERENCES public."Reservations" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Seats_ReservationsId"
    ON public."Seats"("ReservationsId");


ALTER TABLE IF EXISTS public."Seats"
    ADD CONSTRAINT "FK_Seats_Seances_SeanceId" FOREIGN KEY ("SeanceId")
    REFERENCES public."Seances" ("Id") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS "IX_Seats_SeanceId"
    ON public."Seats"("SeanceId");

END;